EducationType.create!(nombre: "Preescolar Rural")
EducationType.create!(nombre: "Preescolar Indigente")
EducationType.create!(nombre: "Preescolar Migrante")
EducationType.create!(nombre: "Primaria Rural")
EducationType.create!(nombre: "Primaria Indigente")
EducationType.create!(nombre: "Primaria Migrante")
EducationType.create!(nombre: "Secundaria Rural")
EducationType.create!(nombre: "Secundaria Indigente")
EducationType.create!(nombre: "CEC")
EducationType.create!(nombre: "CECMI")
EducationType.create!(nombre: "Aula Compartida")
EducationType.create!(nombre: "Albergues")
EducationType.create!(nombre: "CIC")
EducationType.create!(nombre: "Circos")