State.create!(estado: "Colima")
Municipality.create!(municipio: "Armeria", state_id: 1)
Municipality.create!(municipio: "Colima", state_id: 1)
Municipality.create!(municipio: "Comala", state_id: 1)
Municipality.create!(municipio: "Coquimatlan", state_id: 1)
Locality.create!(localidad: "Cofradia de Juarez", municipality_id: 1)
Locality.create!(localidad: "Cuyutlan", municipality_id: 1)
Locality.create!(localidad: "El Paraiso", municipality_id: 1)
Locality.create!(localidad: "Colima", municipality_id: 2)
Locality.create!(localidad: "Acatitlan", municipality_id: 2)
Locality.create!(localidad: "Alpuyequito", municipality_id: 2)
Locality.create!(localidad: "Agosto", municipality_id: 3)
Locality.create!(localidad: "La Becerra", municipality_id: 3)
Locality.create!(localidad: "La Caja", municipality_id: 3)
Locality.create!(localidad: "Agua Zarca", municipality_id: 4)
Locality.create!(localidad: "El Alcomun", municipality_id: 4)
Locality.create!(localidad: "El Algodonal", municipality_id: 4)