SchoolType.create!(educational_level_id: 1, tipo: "Diurna")
SchoolType.create!(educational_level_id: 1, tipo: "Telesecundaria")
SchoolType.create!(educational_level_id: 1, tipo: "Tecnica")
SchoolType.create!(educational_level_id: 1, tipo: "Para Trabajadores")
SchoolType.create!(educational_level_id: 1, tipo: "Comunitaria")
SchoolType.create!(educational_level_id: 1, tipo: "Particular")
SchoolType.create!(educational_level_id: 1, tipo: "Otros")

SchoolType.create!(educational_level_id: 2, tipo: "Colegio Nacional de Educacion Profesional Tecnica")
SchoolType.create!(educational_level_id: 2, tipo: "Colegio de Bachilleres")
SchoolType.create!(educational_level_id: 2, tipo: "Preparatorias Oficiales y Anexas a Escuelas Normales")
SchoolType.create!(educational_level_id: 2, tipo: "Escuela Nacional Preparatoria")
SchoolType.create!(educational_level_id: 2, tipo: "Colegio de Ciencias y Humanidades")
SchoolType.create!(educational_level_id: 2, tipo: "Centro de Educacion Media Superior a Distancia")

SchoolType.create!(educational_level_id: 3, tipo: "Tecnico Superior")
SchoolType.create!(educational_level_id: 3, tipo: "Licenciatura Universitaria")
SchoolType.create!(educational_level_id: 3, tipo: "Licenciatura Tecnologica")
SchoolType.create!(educational_level_id: 3, tipo: "Licenciatura Normal")
SchoolType.create!(educational_level_id: 3, tipo: "Posgtrado")
SchoolType.create!(educational_level_id: 3, tipo: "Particular")
SchoolType.create!(educational_level_id: 3, tipo: "Otros")